// angular/routing/src/app/components/shoppinglist.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:'shoppinglist',
	templateUrl:'./shoppinglist.component.html',
	styleUrls:['./shoppinglist.component.css']
})
export class ShoppingList implements OnInit {

	public shoppinglist:ShoppingItem[] = [];

	constructor(private _shoppingService:ShoppingService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.shoppinglist = this._shoppingService.getList();
	}
	
	
	removeFromList(idx) {
		this._shoppingService.removeFromList(idx);
		this.getList();
	}
	
	editItem(idx) {
	}
}
<table class="table table-striped">
	<thead>
		<tr>
			<th>Type</th>
			<th>Price</th>
			<th>Count</th>
			<th>Remove</th>
			<th>Edit</th>
		</tr>
	</thead>
	<tbody>
		<tr *ngFor="let item of shoppinglist;let idx=index">
			<td>{{item.type}}</td>
			<td>{{item.price}}</td>
			<td>{{item.count}}</td>
			<td><button class="btn btn-primary" (click)="removeFromList(idx)">Buy</button></td>
			<td><button class="btn btn-secondary" (click)="editItem(idx)">Edit</button></td>
		</tr>
	</tbody>
</table>

// vue/shoppinglistaxios/src/views/ShoppingList.vue
<template>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Type</th>
				<th>Count</th>
				<th>Price</th>
				<th>Buy</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>				
			<tr v-for="item in list" :key="item.id">
				<template v-if="editId !== item.id">
					<td>{{item.type}}</td>
					<td>{{item.count}}</td>
					<td>{{item.price}}</td>
					<td><button @click="remove(item.id)" class="btn btn-primary">Buy</button></td>
					<td><button	@click="edit(item.id)" class="btn btn-dark">Edit</button></td>
				</template>
				<template v-else>
					<td><input type="text" v-model="type"/></td>
					<td><input type="number" v-model="count"/></td>
					<td><input type="number" v-model="price"/></td>
					<td><button @click="saveItem()" class="btn btn-success">Save</button></td>
					<td><button @click="cancel()" class="btn btn-danger">Cancel</button></td>
				</template>
			</tr>
		</tbody>
	</table>
</template>

<script>
export default {
	name:"ShoppingList",
	data() {
		return {
			editId:-1,
			type:"",
			count:0,
			price:0
		}
	},
	computed: {
		list:function() {
			return this.$store.state.list
		}
	},
	methods: {
		remove:function(id) {
			this.$store.dispatch('removeFromList',id);
		},
		edit:function(id) {
			this.editId = id;
			for(let i=0;i<this.list.length;i++) {
				if(id === this.list[i].id) {
					this.type = this.list[i].type;
					this.price = this.list[i].price;
					this.count = this.list[i].count;
				}
			}
		},
		cancel:function() {
			this.editId=-1;
			this.type="";
			this.price=0;
			this.count=0;
		},
		saveItem:function() {
			let tempItem = {
				id:this.editId,
				type:this.type,
				price:this.price,
				count:this.count
			}
			this.$store.dispatch("editItem",tempItem);
			this.cancel();
		}
	}
}
</script>
