// angular/services/src/app/components/shoppinglist.component.ts
import {Component,OnInit} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';
import {ShoppingService} from '../services/shoppingservice.service';

@Component({
	selector:'shoppinglist',
	templateUrl:'./shoppinglist.component.html',
	styleUrls:['./shoppinglist.component.css']
})
export class ShoppingList implements OnInit {

	public shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	public shoppinglist:ShoppingItem[] = [];
	public mode = "Add";

	constructor(private _shoppingService:ShoppingService) {}
	
	ngOnInit() {
		this.getList();
	}
	
	getList() {
		this.shoppinglist = this._shoppingService.getList();
	}
	
	addToList() {
		this._shoppingService.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0,0);
		this.getList();
		this.mode = "Add";	
	}
	
	removeFromList(idx) {
		this._shoppingService.removeFromList(idx);
		this.getList();
	}
	
	editItem(idx) {
		this.shoppingitem = this.shoppinglist[idx];
		this.mode = "Edit";
	}
}
<div>
	<h1>Shopping List</h1>
	<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
		<div class="form-group">
			<label for="type">Item type:</label>
			<input type="text"
					name="type"
					[(ngModel)]="shoppingitem.type" 
					id="type"/>
		</div>
		<div class="form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					[(ngModel)]="shoppingitem.price" 
					id="price"/>
		</div>
		<div class="form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					[(ngModel)]="shoppingitem.count" 
					id="count"/>
		</div>
		<button class="btn btn-secondary" type="submit">{{mode}}</button>
	</form>
	<hr/>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Type</th>
				<th>Price</th>
				<th>Count</th>
				<th>Remove</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor="let item of shoppinglist;let idx=index">
				<td>{{item.type}}</td>
				<td>{{item.price}}</td>
				<td>{{item.count}}</td>
				<td><button class="btn btn-primary" (click)="removeFromList(idx)">Buy</button></td>
				<td><button class="btn btn-secondary" (click)="editItem(idx)">Edit</button></td>
			</tr>
		</tbody>
	</table>
</div>

// vue/shoppinglist/src/components/ShoppingList.vue
<template>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Type</th>
				<th>Count</th>
				<th>Price</th>
				<th>Buy</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>					
			<tr v-for="item in list" :key="item.id">
				<template v-if="editId !== item.id">
					<td>{{item.type}}</td>
					<td>{{item.count}}</td>
					<td>{{item.price}}</td>
					<td><button @click="remove(item.id)" class="btn btn-primary">Buy</button></td>
					<td><button	@click="edit(item.id)" class="btn btn-dark">Edit</button></td>
				</template>
				<template v-else>
					<td><input type="text" v-model="type"/></td>
					<td><input type="number" v-model="count"/></td>
					<td><input type="number" v-model="price"/></td>
					<td><button @click="saveItem()" class="btn btn-success">Save</button></td>
					<td><button @click="cancel()" class="btn btn-danger">Cancel</button></td>
				</template>
			</tr>
		</tbody>
	</table>
</template>

<script>
export default {
	name:"ShoppingList",
	props:['list'],
	data() {
		return {
			editId:-1,
			type:"",
			count:0,
			price:0
		}
	},
	methods: {
		remove:function(id) {
			this.$emit('remove-from-list',id);
		},
		edit:function(id) {
			this.editId = id;
			for(let i=0;i<this.list.length;i++) {
				if(id === this.list[i].id) {
					this.type = this.list[i].type;
					this.price = this.list[i].price;
					this.count = this.list[i].count;
				}
			}
		},
		cancel:function() {
			this.editId=-1;
			this.type="";
			this.price=0;
			this.count=0;
		},
		saveItem:function() {
			let tempItem = {
				id:this.editId,
				type:this.type,
				price:this.price,
				count:this.count
			}
			this.$emit("edit-item",tempItem);
			this.cancel();
		}
	}
}
</script>
