// angular/routing/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingService} from '../services/shoppingservice.service';
import {ShoppingItem} from '../models/shoppingitem.model';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	public shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shoppingService:ShoppingService) {}
	
	addToList() {
		this._shoppingService.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0,0);
	}
}
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<div class="form-group">
		<label for="type">Item type:</label>
		<input type="text"
				name="type"
				[(ngModel)]="shoppingitem.type" 
				id="type"/>
	</div>
	<div class="form-group">
		<label for="price">Price:</label>
		<input type="number"
				name="price"
				[(ngModel)]="shoppingitem.price" 
				id="price"/>
	</div>
	<div class="form-group">
		<label for="count">Count:</label>
		<input type="number"
				name="count"
				[(ngModel)]="shoppingitem.count" 
				id="count"/>
	</div>
	<button class="btn btn-secondary" type="submit">Add</button>
</form>

// vue/shoppinglistvuex/src/views/ShoppingForm.vue
<template>
	<div>
		<div class="form form-group">
			<label for="type">Item type:</label>
			<input type="text"
					name="type"
					v-model="item.type"/>
		</div>
		<div class="form form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					v-model="item.count"/>
		</div>	
		<div class="form form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					v-model="item.price"/>
		</div>
		<button class="btn btn-primary" @click="addToList()">Add</button>
	</div>
</template>

<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0			
			}
		}
	},
	methods: {
		addToList:function() {
			this.$store.dispatch("addToList",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0					
			}
		}
	}
}
</script>
