// vue/shoppinglist/src/components/ShoppingForm.vue
<template>
	<div>
		<div class="form form-group">
			<label for="type">Item type:</label>
			<input type="text"
					name="type"
					v-model="item.type"/>
		</div>
		<div class="form form-group">
			<label for="count">Count:</label>
			<input type="number"
					name="count"
					v-model="item.count"/>
		</div>	
		<div class="form form-group">
			<label for="price">Price:</label>
			<input type="number"
					name="price"
					v-model="item.price"/>
		</div>
		<button class="btn btn-primary" @click="addToList()">Add</button>
	</div>
</template>

<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0			
			}
		}
	},
	methods: {
		addToList:function() {
			this.$emit("add-to-list",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0					
			}
		}
	}
}
</script>

// react/hooks/hooks-combined/frontend/src/components/ShoppingForm.js
import React,{useState} from 'react';
import {Form,Button} from 'semantic-ui-react';

const ShoppingForm = ({addToList}) => {
	
	const [item,setItem] = useState({
		type:"",
		const:0,
		price:0
	})
	
	const onChange = (event) => {
		setItem({
			...item,
			[event.target.name]:event.target.value
		})
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		addToList(item);
		setItem({
			type:"",
			count:0,
			price:0
		})
	}
	
	return(
		<Form onSubmit={onSubmit}>
			<Form.Field>
				<label hmtlFor="type">Type</label>
				<input type="text"
						name="type"
						onChange={onChange}
						value={item.type}/>
			</Form.Field>
			<Form.Field>
				<label hmtlFor="count">Count</label>
				<input type="number"
						name="count"
						onChange={onChange}
						value={item.count}/>
			</Form.Field>
			<Form.Field>
				<label hmtlFor="price">Price</label>
				<input type="number"
						name="price"
						onChange={onChange}
						value={item.price}/>
			</Form.Field>
			<Button type="Submit">Add</Button>
		</Form>
	)
}

export default ShoppingForm;
