// react/contactapp/2-step/frontend/src/components/LoginForm.js
import React from 'react';
import {Form,Button} from 'semantic-ui-react';

export default class LoginForm extends React.Component {
	
	constructor(props) {
		super(props);
		this.state = {
			username:"",
			password:""
		}
	}
	
	onChange = (event) => {
		let state = {}
		state[event.target.name] = event.target.value
		this.setState(state);
	}

	onLogin = () => {
		if(this.state.username.length < 4 || this.state.password.length < 8) {
			alert("Username must be four characters and password eight characters long");
			return;
		}
		let user = {
			username:this.state.username,
			password:this.state.password
		}
		this.props.onLogin(user);
	}

	onRegister = () => {
		if(this.state.username.length < 4 || this.state.password.length < 8) {
			alert("Username must be four characters and password eight characters long");
			return;
		}
		let user = {
			username:this.state.username,
			password:this.state.password
		}
		this.props.onRegister(user);
	}
	
	render() {
		return(
			<Form>
				<Form.Field>
					<label htmlFor="username">Username</label>
					<input type="text"
							name="username"
							value={this.state.username}
							onChange={this.onChange}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="password">Password</label>
					<input type="password"
							name="password"
							value={this.state.password}
							onChange={this.onChange}/>
				</Form.Field>
				<Button onClick={this.onRegister}>Register</Button>
				<Button onClick={this.onLogin}>Login</Button>
			</Form>
		)
	}

}

// angular/shoppinglist-ean/src/app/components/loginform.component.ts
import {Component,OnInit} from '@angular/core';
import {LoginService} from '../services/loginservice.service';
import {Router} from '@angular/router';

@Component({
	selector:"loginform",
	templateUrl:"./loginform.component.html"
})
export class LoginForm implements OnInit {
	
	username:string="";
	password:string="";
	message:string="";
	
	constructor(private _login:LoginService, private _router:Router) {}
	
	ngOnInit() {
		if(this._login.isUserLogged()) {
			this._router.navigate(['/list'])
		}
	}
	
	login() {
		if(this.username.length < 4 || this.password.length < 8) {
			this.message = "Username must 4 characters and password 8 characters long"
			return;
		}
		this._login.login(this.username,this.password).subscribe(
			data => {
				this.message = data.message;
				this._login.setLogin(true,data.token);
				this._router.navigate(['/list']);
			},
			error => this.message = error.message,
			() => console.log("login complete")
		)
	}
	
	register() {
		if(this.username.length < 4 || this.password.length < 8) {
			this.message = "Username must 4 characters and password 8 characters long"
			return;
		}
		this._login.register(this.username,this.password).subscribe(
			data => this.message = data.message,
			error => this.message = error.message,
			() => console.log("Register complete")
		)
	}
	
}
<form #loginform="ngForm">
	<label for="username">Username</label>
	<input type="text"
			name="username"
			id="username"
			[(ngModel)]="username"/>
			<br/>
	<label for="password">Password</label>
	<input type="password"
			name="password"
			id="password"
			[(ngModel)]="password"/>
			<br/>
	<button type="button" class="btn btn-primary" (click)="register()">Register</button>
	<button type="button" class="btn btn-primary" (click)="login()">Login</button>
	<h4>{{message}}</h4>
</form>
